POST https://pedantic-kalam-02961d.netlify.app/resolution
Content-Type: application/json

{
   "agent": "Dylan Chua",
   "phone": "6737178007" 
}

#####

DELETE https://pedantic-kalam-02961d.netlify.app/61ef6275a8c509d08582340b

######

PATCH  https://pedantic-kalam-02961d.netlify.app/61ef65e7434cd13d91f62bdc
Content-Type: application/json

{
    "name": "Dylan Chua"
}